version: 0.2
phases:
  install:
    commands:
      - echo "Instalando dependencias..."
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REGISTRY/laravel-app:latest -f Dockerfile.prod .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REGISTRY/laravel-app:latest
