version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80" # Exponemos el puerto 8080 para acceder a la aplicación
        networks:
            - laravel-network
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306" # Exponemos el puerto 3306 para acceder a la base de datos
        networks:
            - laravel-network

    redis:
        image: redis:7.0
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - "6379:6379" # Exponemos el puerto 6379 para Redis
        networks:
            - laravel-network

    mailpit:
        image: axllent/mailpit
        container_name: laravel-mailpit
        restart: unless-stopped
        ports:
            - "1025:1025" # Puerto SMTP
            - "8025:8025" # Interfaz web de Mailpit
        networks:
            - laravel-network

volumes:
    db-data:

networks:
    laravel-network:
        driver: bridge
