version: "3.8"

services:
  app:
    image: 545009837147.dkr.ecr.us-east-2.amazonaws.com/laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"       # Mapea el puerto 80 del host al 80 del contenedor
      - "5173:5173"   # Opcional: si requieres Vite HMR en producción
    networks:
      - laravel-network
    environment:
      # Configura las variables de entorno necesarias para Laravel.
      # Ejemplo:
      # DB_HOST: ${RDS_ENDPOINT}
      # DB_DATABASE: laravel
      # DB_USERNAME: admin
      # DB_PASSWORD: <tu_contraseña>
  mailpit:
    image: axllent/mailpit
    container_name: laravel-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
