AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # Repositorio ECR para Docker
  MyECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: laravel-app
  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: mi-llave-ec2 
      PublicKeyMaterial: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILz9f+Qwsl4LArAINi8uyx99QSJ0vK5Vt1t5AMUho4Uu nunezjuliot@gmail.com

  # Instancia EC2 con Docker preinstalado
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316 # Ubuntu 22.04
      InstanceType: t2.micro
      KeyName: mi-llave-ec2 # Se creará automáticamente
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt update
          apt install -y docker.io docker-compose
          usermod -aG docker ubuntu
          systemctl enable docker

  # Base de datos RDS (MySQL)
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: laravel-db
      MasterUsername: admin
      MasterUserPassword: password
      DBName: laravel
      Engine: mysql
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      PubliclyAccessible: true

  # Grupos de seguridad
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso a EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Roles y políticas de IAM
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                  - s3:*
                  - ec2:*
                Resource: "*"
        - PolicyName: CloudFormationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"