AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso HTTP/SSH a EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
    DeletionPolicy: Delete

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso RDS desde EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt EC2SecurityGroup.GroupId
    DeletionPolicy: Delete

  MyEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - EC2SecurityGroup
    Properties:
      ImageId: ami-0d0f28110d16ee7d6  # AMI de Amazon Linux 2
      InstanceType: t2.micro
      KeyName: KeypairGithub
      SecurityGroupIds:
        - !GetAtt EC2SecurityGroup.GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -aG docker ec2-user
          chkconfig docker on
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
    DeletionPolicy: Delete

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - RDSSecurityGroup
    Properties:
      DBInstanceIdentifier: laravel-db
      MasterUsername: admin
      MasterUserPassword: "{{resolve:ssm-secure:/laravel/db/password}}"
      DBName: laravel
      Engine: mysql
      EngineVersion: "5.7.44"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
    DeletionPolicy: Snapshot

Outputs:
  MyEC2InstancePublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp
  RDSEndpoint:
    Description: "Endpoint of the RDS instance"
    Value: !GetAtt MyRDSInstance.Endpoint.Address
